defaults: &defaults
  domain: "sse.se.rit.edu"
  repository: "https://github.com/codykrieger/pinocchio.git"
  rake_env:
    #RAILS_ENV: 'production'

staging:
  <<: *defaults
  deploy_to: "~/staging.pinocchio"
  post_setup_script: 'script/post-setup-staging.sh'

production:
  <<: *defaults
  deploy_to: "~/pinocchio"
  post_setup_script: 'script/post-setup-production.sh'
  post_deploy_script: 'script/post-deploy.sh'

